package dev.pranav.bryte.server.ai.koog

import ai.koog.agents.core.agent.AIAgent
import ai.koog.agents.core.agent.AIAgent.Companion.State
import ai.koog.agents.core.agent.AIAgent.Companion.State.NotStarted
import ai.koog.agents.core.agent.context.AIAgentContext
import ai.koog.agents.core.agent.context.element.AgentRunInfoContextElement
import ai.koog.agents.core.agent.entity.AIAgentStrategy
import ai.koog.agents.core.annotation.InternalAgentsApi
import ai.koog.agents.core.feature.AIAgentFeature
import ai.koog.agents.core.feature.pipeline.AIAgentPipeline
import io.github.oshai.kotlinlogging.KLogger
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlin.reflect.KClass
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Abstract base class representing a stateful AI agent capable of **multiple, consecutive uses**. 🔄
 *
 * This agent executes a specific strategy multiple times. **It retains its internal
 * context, features, and resources (like an LLM session)** between calls, enabling conversational flow
 * or multi-step, stateful interactions.
 *
 * It tracks the state of the **most recent execution** and manages the lifecycle of shared resources.
 *
 * @param Input the type of the input accepted by the agent.
 * @param Output the type of the output produced by the agent.
 * @param TContext the type of the context used during the agent's execution, extending [AIAgentContext].
 * @property logger the logger used for logging execution details and errors.
 * @param id the unique identifier for the agent. Random UUID will be generated if set to null.
 */
@OptIn(ExperimentalUuidApi::class)
public abstract class StatefulAIAgent<Input, Output, TContext : AIAgentContext>(
    protected val logger: KLogger,
    id: String? = null,
) : AIAgent<Input, Output> {
    /**
     * A mutex used to synchronize access to the state of the agent.
     */
    private val agentStateMutex: Mutex = Mutex()

    private var state: State<Output> = NotStarted()

    // --- State for Persistent Context Management ---
    // This is the key state that ensures resources (like the LLM session) are only prepared once.
    private val resourceInitializationMutex: Mutex = Mutex()
    private var isResourceInitialized: Boolean = false
    // --- End State for Persistent Context Management ---

    final override suspend fun getState(): State<Output> = agentStateMutex.withLock { state.copy() }

    final override val id: String by lazy { id ?: Uuid.random().toString() }

    /**
     * The execution strategy defining how the agent processes input and produces output.
     */
    public abstract val strategy: AIAgentStrategy<Input, Output, TContext>

    /**
     * Represents the pipeline used by the AI agent for processing tasks or data.
     */
    protected abstract val pipeline: AIAgentPipeline

    /**
     * Executes the agent's main functionality.
     * **Allows multiple calls** and preserves session context across them.
     *
     * @param agentInput The input required to execute the agent's strategy.
     * @return The output generated by the agent's execution.
     * @throws Throwable if any exception occurs during the execution process.
     */
    final override suspend fun run(agentInput: Input): Output {
        // 1. State Update for New Run
        agentStateMutex.withLock {
            state = State.Starting()
        }

        val runId = Uuid.random().toString()
        val context = prepareContext(agentInput, runId)

        return withContext(
            AgentRunInfoContextElement(
                agentId = id,
                runId = runId,
                agentConfig = agentConfig,
                strategyName = strategy.name
            )
        ) {
            // 2. Resource/Pipeline Management for Persistence (Crucial Difference)
            // Only prepare features (which might initialize the LLM session) on the first run.
            resourceInitializationMutex.withLock {
                if (!isResourceInitialized) {
                    pipeline::class.java.getMethod("prepareAllFeatures").invoke(pipeline)
                    isResourceInitialized = true
                }
            }

            // The rest of the execution logic runs without closing resources.
            try {
                agentStateMutex.withLock {
                    state = State.Running(context)
                }

                logger.debug { formatLog(agentId = id, runId = runId, message = "Starting agent execution") }

                // The original implementation assumes the current class is available via 'this@AIAgent' or similar.
                pipeline.onAgentStarting<Input, Output>(
                    runId = runId,
                    agent = this@StatefulAIAgent,
                    context = context
                )

                val result = try {
                    strategy.execute(context = context, input = agentInput)
                } catch (e: Throwable) {
                    logger.error(e) { "Execution exception reported by server!" }
                    pipeline.onAgentExecutionFailed(agentId = id, runId = runId, throwable = e)
                    agentStateMutex.withLock { state = State.Failed(e) }
                    throw e
                }

                logger.debug { formatLog(agentId = id, runId = runId, message = "Finished agent execution") }

                pipeline.onAgentCompleted(agentId = id, runId = runId, result = result)

                agentStateMutex.withLock {
                    state = result?.let { State.Finished(it) } ?: State.Failed(Exception("result is null"))
                }

                result ?: error("result is null")

            } catch (e: Throwable) {
                // Ensure state is updated to failed if any unhandled error occurs
                agentStateMutex.withLock {
                    if (state !is State.Failed) {
                        state = State.Failed(e)
                    }
                }
                throw e
            }
        }
    }

    /**
     * Closes the AI Agent and performs necessary cleanup operations, **releasing persistent resources**.
     * This is where the LLM session and context resources are finally closed.
     */
    final override suspend fun close() {
        resourceInitializationMutex.withLock {
            if (isResourceInitialized) {
                pipeline.onAgentClosing(agentId = id)
                // This call ensures the persistent features (like the LLM session) are closed.
                pipeline::class.java.getMethod("closeAllFeaturesMessageProcessors").invoke(pipeline)
                isResourceInitialized = false
            }
        }
    }

    /**
     * Prepares and initializes the agent context required to handle the given input and run ID.
     * This method is **abstract** and must be implemented by subclasses.
     */
    public abstract suspend fun prepareContext(agentInput: Input, runId: String): TContext

    /**
     * Retrieves a feature from the agent's pipeline associated with this agent using the specified key.
     */
    public fun <TFeature : Any> feature(
        featureClass: KClass<TFeature>,
        feature: AIAgentFeature<*, TFeature>
    ): TFeature? = pipeline.feature(featureClass, feature)

    /**
     * Formats a log message with the specified agent ID, run ID, and message content.
     */
    protected fun formatLog(agentId: String, runId: String, message: String): String =
        "[agent id: $agentId, run id: $runId] $message"
}

// --- Companion functions copied for utility ---

/**
 * Retrieves a feature from the [StatefulAIAgent.pipeline] associated with this agent using the specified key.
 */
public inline fun <reified TFeature : Any> StatefulAIAgent<*, *, *>.feature(
    feature: AIAgentFeature<*, TFeature>
): TFeature? = feature(TFeature::class, feature)

/**
 * Retrieves a feature from the [StatefulAIAgent.pipeline] associated with this agent using the specified key
 * or throws an exception if it is not available.
 */
public inline fun <reified TFeature : Any> StatefulAIAgent<*, *, *>.featureOrThrow(
    feature: AIAgentFeature<*, TFeature>
): TFeature = feature(feature) ?: throw NoSuchElementException("Feature ${feature.key} is not found.")

